### Site info:
title: Dr. Hamdi Kavak
tagline: Advancing modeling and simulation theory, methodology, and practice — one challenge at a time.
author: Dr. Hamdi Kavak
email: hkavak@gmu.edu
description: "Dr. Hamdi Kavak's Home Page" # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "hamdi kavak, data-driven modeling, agent-based simulation, data-driven agents"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://hamdikavak.com" # the base hostname & protocol for your site
locale: en_US

### Personal info and site tools info:
twitter_username: hmdkvk
github_username:  hamdikavak
researchgate_username: Hamdi_Kavak
scholar_url: http://scholar.google.com/citations?user=udTYdPAAAAAJ
youtube_channel: UCBijHAVQUO2c9uqCXX3t8Tg
#disqus_shortname: -
favicon:     "/images/favicon.ico"
aboutme: Dr. Hamdi Kavak is an Assistant Professor at George Mason University. # these are shown on aboutme-sidebar.
aboutme_photo: https://pbs.twimg.com/profile_images/718186961865977856/zXirhM2T_400x400.jpg
google_analytics_key:  # put YOUR key here to enable tracking! (blank to disable)
thumbnail_width: 160

### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown where ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English (en), Chinese (cn), Japanese (jp), Polish (pl), Korean (kr),  Russian (ru), Turkish (tr), and Indonesian (id).


locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"
      PostDate: "on "
      Google_search: "Site Search"
      Home: "Home"
      About: "About"
      Guestbook: "Guestbook"
      Subscribe: "Subscribe"
      Research: "Research"
      Teaching: "Teaching"
      Publications: "Publications"
      Students: "Students"
      Summer_2021: "Summer 2021"
    cn:
      Aboutme: "关于我"
      Archives: "存档"
      Blogroll: "良师益友"        
      Categories: "分类目录"    
      Copyright_Notice: "版权声明"
      Recent_Posts: "近期文章"
      Tags: "标签" 
      Previous: "前一页"
      Next: "后一页"
      PostedInCategories: "目录:"   
      Taggedwith: "| 标签:"
      PostDate: "| 发表时间: "
      Google_search: "站内搜索"
      Home: "首页"
      About: "关于"
      Guestbook: "留言"
      Subscribe: "订阅"
      Research: "Research"
      Teaching: "Teaching"
      Publications: "Publications"
      Students: "Students"
      Summer_2021: "Summer 2021"
    jp:
      Aboutme: "著者"
      Archives: "アーカイブ"
      Blogroll: "ブログロール"
      Categories: "カテゴリー"
      Copyright_Notice: "著作権表示"
      Recent_Posts: "最近の投稿"
      Tags: "タグ"
      Previous: "前の記事"
      Next: "次の記事"
      PostedInCategories: "カテゴリー："
      Taggedwith: "| タグ："
      PostDate: "| 投稿日時: "
      Google_search: "サイト内検索"
      Home: "ホーム"
      About: "このブログについて"
      Guestbook: "メッセージ"
      Subscribe: "購読"
      Research: "Research"
      Teaching: "Teaching"
      Publications: "Publications"
      Students: "Students"
      Summer_2021: "Summer 2021"
    pl:
      Aboutme: "O mnie"
      Archives: "Archiwum"
      Blogroll: "Odnośniki"
      Categories: "Kategorie"
      Copyright_Notice: "Prawa autorskie"
      Recent_Posts: "Najnowsze wpisy"
      Tags: "Tagi"
      Previous: "Starsze"
      Next: "Nowsze"
      PostedInCategories: "Kategoria"
      Taggedwith: "tagi"
      PostDate: "on "
      Google_search: "Wyszukiwarka"
      Home: "Strona główna"
      About: "O mnie"
      Guestbook: "Księga gości"
      Subscribe: "Subskrypcja"
      Research: "Research"
      Teaching: "Teaching"
      Publications: "Publications"
      Students: "Students"
      Summer_2021: "Summer 2021"
    kr:
      Aboutme: "저자 소개"
      Archives: "모든 게시물"
      Blogroll: "참조 링크"
      Categories: "카테고리"
      Copyright_Notice: "저작권"
      Recent_Posts: "최근 게시물"
      Tags: "태그"
      Previous: "이전 게시물"
      Next: "다음 게시물"
      PostedInCategories: "카테고리: "
      Taggedwith: "태그: "
      PostDate: "작성일: "
      Google_search: "게시물 검색"
      Home: "홈"
      About: "소개"
      Guestbook: "방명록"
      Subscribe: "구독하기"
      Research: "Research"
      Teaching: "Teaching"
      Publications: "Publications"
      Students: "Students"
      Summer_2021: "Summer 2021"
    ru:
      Aboutme: "Обо мне" # = 'About me'
      Archives: "Архив"
      Blogroll: "Ссылки" # = 'Links'
      Categories: "Разделы"
      Copyright_Notice: "Авторские права"
      Recent_Posts: "Свежие посты"
      Tags: "Теги"
      Previous: "Предыдущий пост"          # = 'Previous post'
      Next: "Следующий пост"               # = 'Next post'
      PostedInCategories: "Опубликовано в" # = 'Posted in'
      Taggedwith: "с тегами"
      PostDate: ""
      Google_search: "Поиск на Google"
      Home: "Домой"
      About: "О блоге"            # = 'About blog'
      Guestbook: "Гостевая книга"
      Subscribe: "Подписаться"
      Research: "Research"
      Teaching: "Teaching"
      Publications: "Publications"
      Students: "Students"
      Summer_2021: "Summer 2021"
    tr:
      Aboutme: "Hakkımda"
      Archives: "Arşivler"
      Blogroll: "Bağlantılar"
      Categories: "Kategoriler"
      Copyright_Notice: "Telif Hakkı Bildirimi"
      Recent_Posts: "Son Yazılar"
      Tags: "Etiketler"
      Previous: "Daha Eski"
      Next: "Daha Yeni"
      PostedInCategories: "Şuraya gönderildi:"
      Taggedwith: "ve şöyle etiketlendi:"
      PostDate: "şu tarihte:"
      Google_search: "Sitede Ara"
      Home: "Anasayfa"
      About: "Hakkında"
      Guestbook: "Konuk Defteri"
      Subscribe: "Abone Ol"
      Research: "Araştırma"
      Teaching: "Dersler"
      Publications: "Yayınlar"
      Students: "Oğrenciler"
      Summer_2021: "Summer 2021"
    id:
      Aboutme: "Tentang Saya"
      Archives: "Arsip"
      Blogroll: "Blog teman"
      Categories: "Kategori"
      Copyright_Notice: "Legal Formal"
      Recent_Posts: "Post Terkini"
      Tags: "Tag"
      Previous: "Lebih lama"
      Next: "Lebih baru"
      PostedInCategories: "Diposting di"
      Taggedwith: "dan ditag"
      PostDate: "pada "
      Google_search: "Pencarian Situs"
      Home: "Beranda"
      About: "Tentang"
      Guestbook: "Buku tamu"
      Subscribe: "Langganan"
      Research: "Research"
      Teaching: "Teaching"
      Publications: "Publications"
      Students: "Students"
      Summer_2021: "Summer 2021"

### your Blogroll info, only name can shown on the page.

Blogroll:
      - name: Dr. Hamdi Kavak
        href: http://hamdikavak.com/hamdikavakcomtest
        title: Dr. Hamdi Kavak's Home Page
      - name: Dr. Hamdi Kavak's website
        href: http://hamdikavak.com/hamdikavakcomtest
        title: Dr. Hamdi Kavak's website


### Build settings
markdown: kramdown
#highlighter: pygments
kramdown:
        input: GFM
        syntax_highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5
excerpt_separator: <!-- more -->
